openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java

This PR cherrypick changes from #9 on 1.1.x

Cherrypick PR #9 Set the operation summary by default to the javadocDescription

---

openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

Updated OpenApiApplicationVisitor to handle multiple content types in a response, request body, and parameters.

Handle multiple content types

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy

Updated `annotationValueArrayToSubmap` to set name to "application/json" if classifier is mediaType and name is not defined on annotation value.

Fix #14 OpenAPI - schema annotation in ApiResponse is not used

---

src/main/docs/guide/introduction.adoc

The swagger yaml that is being produced is, as of Micronaut 1.1.1 and May 15, 2019, OpenAPI 3.0.1.
Thus, code and documentation should be updated to 3.x.

Swagger 2.x to Swagger 3.x

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiApplicationVisitorSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiMergeSchemaSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationParseSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSecurityRequirementSpec.groovy

According to https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#securityRequirementObject and Swagger UI
Correct format should be:
```
custom_name:
- scope1
- scope2
```
not
```
name:
- custom_name
scopes:
- scope1
- scope2 
```

Correct security requirement object definition

---

openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

From Micronaut 1.2.0, Completable is supported as controller return type (https://docs.micronaut.io/latest/guide/introduction.html#_completable_support)
The completable response should not have body, so the default response should be left empty.

Completable response does not have body

---

openapi/src/main/java/io/micronaut/openapi/javadoc/JavadocParser.java
openapi/src/test/groovy/io/micronaut/openapi/javadoc/JavadocParserSpec.groovy

Previously it switched to TEXT state on newline which would add remainder to description.
Fixes #45

Return value should be allowed to be multiline

---

openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiParameterMappingSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

When the generated yml file is validated, a bunch of errors show up because the default response description is missing. This issue is also mentioned in #46 
I'm not sure what is a sensible default response description, so I choose `openrationId + " default response"`
This PR also add an assert for the test case when requestBody is null

Default response description is required

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationParseSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/SchemaMetaAnnotationSpec.groovy

Added support for @ExampleObject and @RequestBody annotations, as well as jsons nested as a String (to be parsed by yaml)

Support for @ExampleObject and @RequestBody

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

https://github.com/micronaut-projects/micronaut-openapi/pull/65
introduces support for 'requiredProperties' attribute, but it can lead to have duplicate entries
in the generated yaml.

Fix duplicate required properties

---

openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/resources/templates/rapidoc/index.html
openapi/src/main/resources/templates/redoc/index.html
openapi/src/main/resources/templates/swagger-ui/index.html
openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiViewParseSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiViewRenderSpec.groovy
src/main/docs/guide/openApiViews.adoc
src/main/docs/guide/toc.yml

Currently, views for swagger-ui, redoc and rapidoc are supported.

Add option to generate views for generated OpenApi yaml.

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiInheritedPojoControllerSpec.groovy

Given the following classes with an `allOf`
```java
@Schema(description = "A")
public class A {
@Schema(description = "a")
@Nullable
private String a;
public String getA() {
return a;
}
public void setA(String a) {
this.a = a;
}
}
@Schema(description = "B", allOf = A.class)
public class B extends A {
@Schema(description = "b")
@Nullable
private String b;
public String getB() {
return b;
}
public void setB(String b) {
this.b = b;
}
}
```
Micronaut generates
```
components:
schemas:
A:
type: object
properties:
a:
type: string
description: a
nullable: true
description: A
B:
type: object
properties:
b:
type: string
description: b
nullable: true
description: B
allOf:
- $ref: '#/components/schemas/A'
```
While what is expected is:
```
components:
schemas:
A:
type: object
properties:
a:
type: …
```

allOf is not appearing properly in generated schema

---

travis-build.sh

It seems like each time we merge a PR in either master or 1.2.x branch then the snapshot documentation gets updated which shows inconsistent behavior. 
For instance, we have updated the documentation in the master branch to support Swagger UI views which is missing right now as the snapshot is pointing to 1.2.x.

Publish snapshots for master only

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileUploadBodyParameterSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileUploadSpec.groovy

As micronaut uses StreamingFileUpload, CompletedFileUpload or PartData, this lead to special cases when generating the spec file.
refs: 
- https://swagger.io/docs/specification/describing-request-body/file-upload/
- https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#considerations-for-file-uploads
These are the currently supported cases
```java
@Controller("/")
class UploadController {
/**
* Single streaming file upload. Receiving PartData.
* @param file The file parts.
* @return nothing.
*/
@Post(value = "/receive-flow-control", consumes = MediaType.MULTIPART_FORM_DATA, produces = MediaType.TEXT_PLAIN)
Single<String> partData(Flowable<PartData> file) {
return Single.just("");
}
/**
* Single file upload. Receiving CompletedFileUpload.
* @param file The complete …
```

Add support for multipart/form-data file upload.

---

openapi/src/main/resources/templates/rapidoc/index.html
openapi/src/main/resources/templates/redoc/index.html
openapi/src/main/resources/templates/swagger-ui/index.html
src/main/docs/guide/openApiViews.adoc

Some logic added for the open views to work in case a server context path is defined
You need to pass a parameter to the view with the defined context path:
http://localhost:8080/context/path/swagger-ui?contextPath=%2Fcontext%2Fpath.

Context path aware openapi views.

---

openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
src/main/docs/guide/controllersAndSwaggerAnnotations.adoc

Should fix https://github.com/micronaut-projects/micronaut-openapi/issues/24
based on the following:
https://gist.github.com/silas/3b41e6ed4031c11f919767a74829ffea
https://github.com/swagger-api/swagger-core/blob/26d72bf5fd2d54e5e514ddcf3861d125d2f95b42/modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/SnakeCaseConverterTest.java
Uses a system property to specify the schema naming strategy property.

Specify Property naming strategy a compile time.

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationParseSpec.groovy

In OpenAPI mixed type arrays can be defined using `oneOf` as:
```
type: array
items:
oneOf:
- type: string
- type: integer
```
Currently, it is not possible with Micronaut OpenAPI where if an operation returns mixed type array such as:
```
@Controller("/pet")
interface PetOperations {
@Operation(summary = "Get a list of pets",
description = "Get a list of pets registered in the system",
responses = {@ApiResponse(responseCode = "200",
description = "The response for the pet request",
content = @Content(mediaType = MediaType.APPLICATION_JSON,
array = @ArraySchema(schema = @Schema(oneOf = {Cat.class, Dog.class}))
)
)}
)
@Get
List<? extends Pet> list();
}
```
The generated OpenAPI YAML contains incorrect information:
```
paths:
/pet:
get:
summary: Get a list of pets
description: Get a list of …
```

Support mixed type arrays

---

src/main/docs/guide/openApiViews.adoc

For Groovy + Maven project the system properties are not passed from `compilerArgs` configuration parameter of "maven-compiler-plugin" and instead we need to set 'micronaut.openapi.views' system property via properties-maven-plugin > set-system-properties.
Here is the [Sample Application](https://github.com/puneetbehl/maven-groovy-swagger)

#108 Updated Views Documentation

---

openapi/src/main/java/io/micronaut/openapi/util/Yaml.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiParameterMappingSpec.groovy

A parameter with no annotation is considered as a PathVariable.
https://github.com/micronaut-projects/micronaut-openapi/issues/130

Issue # 130 - Case 2

---

openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
openapi/src/main/java/io/micronaut/openapi/view/RapiPDFConfig.java
openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
openapi/src/main/java/io/micronaut/openapi/view/RedocConfig.java
openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
openapi/src/main/resources/templates/rapidoc/index.html
openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiViewParseSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiViewRenderSpec.groovy
src/main/docs/guide/openApiViews.adoc

rapipdf allows to generate a PDF from a spec file (in the browser).
Adds a button to rapidoc view when enabled.

Add support for rapipdf

---

openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java

I'm somewhat confused by this problem. I have a project where I'm merging in a custom made openapi file containing schemas to replace the micronaut-generated schemas. Since the object schemas being replaced are `@AutoValue` objects that don't lend themselves well for generation like ordinary beans do, this for now seems like the easiest option to achieve a full openapi spec.
Trying it out with a simple proof of concept, this seems to work well. However when I implement the same thing in the greater project, every Schema that I'm trying to overwrite has a null reference. (i.e. `#/components/schemas/null`, rather than `#/components/schemas/Foo`). I haven't been able to figure out why this should be the case (as I'm having trouble debugging this issue, maven's forked compile goal seems to …

Ensure the Schema name isn't null when merged in

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationParametersSpec.groovy

to 'enum' and 'default' for schema model.
Should fix https://github.com/micronaut-projects/micronaut-openapi/issues/145

remap 'allowableValues' and 'defaultValue'

---

openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java

when rendering openapi views (swagger-ui, ...) with user define target (micronaut.openapi.target.file)

Use absolute path to avoid NullPointerException

---

openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiViewRenderSpec.groovy

https://github.com/micronaut-projects/micronaut-openapi/pull/170
add the ablity to add context path at compile time by prepending openapi spec paths with it
but was missing adding context-path to spec-url in generated views.

Fix: server context must be added to spec-url

---

src/main/docs/guide/openApiViews.adoc

There is a possibilitiy to add arguments directly to kapt, not only through system properties.

Added kapt config for Kotlin projects basedo on gradle

---

gradle/wrapper/gradle-wrapper.properties
openapi/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElementExt.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiArraySchemaSpec.groovy

Unfortunately it does not work for $ref, swagger ignore all others properties when set:
https://github.com/swagger-api/swagger-core/blob/1aa6f1f82c5a3e7e075e8dba606d2210da70a097/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/SchemaSerializer.java#L29
```java
@Override
public void serialize(
Schema value, JsonGenerator jgen, SerializerProvider provider)
throws IOException {
// handle ref schema serialization skipping all other props
if (StringUtils.isBlank(value.get$ref())) {
defaultSerializer.serialize(value, jgen, provider);
} else {
jgen.writeStartObject();
jgen.writeStringField("$ref", value.get$ref());
jgen.writeEndObject();
}
}
```

Issue #274 - Take schema description from class javadoc.

---

src/main/docs/guide/gettingStarted.adoc

As of the 2.0.0 release it appears that the maven group was changed to io.micronaut.openapi.

Change the group id of the openapi dependency

---

src/main/docs/guide/openApiViews.adoc

In a multi-module gradle project that used Kotlin with a kotlin script file instead of a groovy script file, I was able to successfully generate the Open API views when setting the `org.gradle.jvmargs` property. This allowed me to not have to use the environment variable approach to generate the views correctly. When trying to use the `kapt` block in my `build.gradle.kts`, I could not successfully generate the views.

#108 Generating an OpenAPI view with Kotlin

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

Fixes https://github.com/micronaut-projects/micronaut-openapi/issues/286
`$` is not allowed by OpenApi: `Component names can only contain the characters A-Z a-z 0-9 - . _`

Generate schema for inner classes with `dot` instead of `dollar`

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiInheritedPojoControllerSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationHeadersSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationLinkSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationParseSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaGenericsSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaInheritanceSpec.groovy
src/main/docs/guide/controllersAndSwaggerAnnotations.adoc

https://swagger.io/docs/specification/describing-responses/ specifies that the status code should be the response key.
Also improves how `@ApiResponse` can be used, if one found with the same status code or `default` it will be used. 
The content is set if it's missing.
Fixes https://github.com/micronaut-projects/micronaut-openapi/issues/215

Generate response mapping with status code instead of "default"

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiRequestBeanSpec.groovy

As title says this adds support for `@RequestBean` and closes https://github.com/micronaut-projects/micronaut-openapi/issues/345.
Fairly simple implementation: for every field of RequestBean class `processParameter` method is called. The only inconvenience is that I had to change some usages of `ParameterElement` to  `TypedElement`.

Add support for @RequestBean

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiDateTimeExampleSchemaSpec.groovy

Currently Body arguments are accepting both @Nullable as Optional argument to be recognised as non required arguments.
For method @Parameters, this is only considered for @Nullable. With this fix, it will also accept Optional.

Allow Optional arguments to be recognised as non-required

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

This change comes as a proposition to address following comment:
https://github.com/micronaut-projects/micronaut-openapi/pull/346#issuecomment-721863733
It is practically inspited from #368, by recursively resolving schemas.
Note: recursive calls to `resolveSchema` specify the immediate outer class element as `definingElement`.

Fix generation of to-array dictionaries

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiRequestBeanSpec.groovy

I changed the test code so that it defines the name of the header using a constant, the test failed.
Ignoring static fields fixed the test.

#392 - Improved support for @RequestBean. Ignore static fields/constants

---

src/main/docs/guide/controllersAndSwaggerAnnotations.adoc

In a Kotlin only project the system property `micronaut.openapi.property.naming.strategy` can be set in the `gradle.properties` file and will reflect the changes in the generated open api yml file.

Documentation change for PropertyNamingStrategy

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOutputYamlSpec.groovy

Fixes #409. 
Note: I first tried with: 
```
OpenApi sortOpenApi(OpenApi openApi) {
yaml = serialize(openApi)
return deserlialize(yaml)
}
```
But in that case some unit tests failed, since OpenApi ObjectMapper Deserializator does not handle some openApi cases that are written by hand in Unit tests. So some fields that Unit tests expect were not present in sorted deserialized OpenApi object. 
After that I decided to check actual raw yaml output in tests.

#409 - Set consistent ordering for yaml map properties

---

openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/resources/templates/swagger-ui/index.html
openapi/src/main/resources/templates/swagger-ui/oauth2-redirect.html
openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiViewRenderSpec.groovy
src/main/docs/guide/oauth2.adoc
src/main/docs/guide/openApiViews.adoc
src/main/docs/guide/toc.yml

Fixes #422
Fixes #428
Fixes #437

Implement OAuth 2 support

---

src/main/docs/guide/gettingStarted.adoc
src/main/docs/guide/swaggerAnnotations.adoc

Dependency swagger-annotations version of io.swagger.core.v3 isn't the same version as Micronaut. 
If you select version 2.5.0 in the docs, for example, there's no 2.5.0 of swagger-annotations in the maven repository.

Remove swagger-annotations version

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiBasicSchemaSpec.groovy

This PR fixes issue #363. I added support for READ_ONLY and WRITE_ONLY accessModes in the Schema annotation.
Setting accessMode to READ_ONLY sets the schema's readOnly attribute to true.
Setting accessMode to WRITE_ONLY sets the schema's writeOnly attribute to true.

fixes #363 adds support for schema READ_ONLY and WRITE_ONLY accessModes

---

openapi/build.gradle
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileResponseTypeSpec.groovy

Generate correct openapi when returning a StreamedFile

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiBasicSchemaSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOutputYamlSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

Fixes #409
It turns out that at the end this is not a breaking change. As you can see in the modified tests I only needed to make some minor adjustments, so I think this fix can go in a patch release.
---
According to https://swagger.io/docs/specification/data-models/data-types/#required
all object properties are optional by default, so if a fields is not
nullable, it should be declared as "required" in the OpenAPI spec file.
In case the `@Schema` annotation exists on the field, it takes
precendece because the user decided to use it. It's up to the user to
make sure that the annotations in the field and in the constructor are
the same so they make sense.

All not nullable parameters in a constructor are required in OpenAPI

---

openapi/src/main/java/io/micronaut/openapi/postprocessors/JacksonDiscriminatorPostProcessor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiJacksonVisitor.java
openapi/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiInheritedPojoControllerSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiJacksonInheritanceSpec.groovy

Fixes #508
This PR fixes the generated openapi to handle properly Jackson `@JsonTypeInfo` and `@JsonSubTypes` with inheritance when no `@Schema` annotations are used.
Before this PR, using the sample application code provided in the issue, the openapi rendered with ReDoc looked like:
Only the `id` from the `Pet` interface was used but no the specific fields from children `Dog` and `Cat`.
Now with this PR when selecting a Cat/Dog the right properties are displayed. Also the discriminator `type` is there.

Support inheritance for request and response body with Jackson

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiParameterMappingSpec.groovy

Follow up on #416
If a parameter is added at method level using `@Parameter` annotation
and also declared as method argument it can't be added twice. The one
declared in the `@Parameter` annotation takes precedences over the one
declared as method argument.

Do not duplicate parameters when defined twice

---

openapi/build.gradle
openapi/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElementExt.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java

This change proposes to address the few remaining deprecation warnings as suggested by micronaut API's javadoc:
* `ClassElement.getFields` -> `ClassElement.getEnclosedElements(ALL_FIELDS)`
* `JavaPropertyElement(..., ExecutableElement, ...)` -> `JavaPropertyElement(..., Element, ...)`
* `VisitorContext.visitMetaInfFile(String)` -> `VisitorContext.visitMetaInfFile(String, EMPTY_ELEMENT_ARRAY)`
The `-deprecation` option is only added to help locate future deprecation warnings.

Fix deprecation warnings

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

Fixes #555
Fixes #564
This was changed in https://github.com/micronaut-projects/micronaut-openapi/pull/540/files#diff-70483a9ff868dce418c3a545df1929d1c33a917d15e9bcc650b3e5185166b909L1120 and led to this issue. Now the change is reverted and I've added a test for it.

Use getDeclaredAnnotation when retrieving @Schema

---

docs-examples/example-kotlin/build.gradle
gradle.properties

Bumps org.jetbrains.kotlin.jvm from 1.5.21 to 1.5.30.
---
updated-dependencies:
- dependency-name: org.jetbrains.kotlin.jvm
dependency-type: direct:production
update-type: version-update:semver-patch
...
Signed-off-by: dependabot[bot] <support@github.com>- Bump org.jetbrains.kotlin.jvm from 1.5.21 to 1.5.30
- Bump org.jetbrains.kotlin.kapt from 1.5.21 to 1.5.30
- Upgrade Kotlin to 1.5.30

Upgrade Kotlin to 1.5.30

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

Fixes #611
Fixes #632
Waiting on feedback from users before merging it. See https://github.com/micronaut-projects/micronaut-openapi/issues/611#issuecomment-1005511919

`@Schema` annotation takes precedence over nullability annotations

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

Before code fix when there are multiple `@ApiResponse` annotations present on one of the Controller classes, content section for response with status 200 wasn't generated.  This should fix #656.

Fix bug with multiple @ApiResponse

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiRecursionSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaInheritanceSpec.groovy

This code change fixes issue with inheritance of "description" and "nullable" attributes. The fields annotated with `@Schema` should always consider their "description" and "nullable" arguments. The "required" argument should be only displayed in the list of the required properties of the DTO.
Fix #659

Multiple bug fixes with proper attribute inheritance

---

src/main/docs/guide/serverContext.adoc
src/main/docs/guide/serverContext/compileResolution.adoc
src/main/docs/guide/serverContext/serverFilter.adoc
src/main/docs/guide/serverContext/urlParameter.adoc
src/main/docs/guide/toc.yml

As suggested in micronaut-projects/micronaut-core#6905 I have updated the documentation to include a way to handle dynamic context-paths at runtime.
This is very useful if the same build artifact is intended to run behind multiple reverse proxies (e.g. on different stages) which serve the application on different context-paths.
The idea is to parse the context-path from the request headers. This assumes that the reverse proxy is configured to set the header accordingly.
Unfortunately, I could not test if the docs still compile correctly. If there is an easy way to test that, I'm happy to do so. Just let me know.

update server-context documentation

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiNullableTypesSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiRecursionSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaInheritanceSpec.groovy

First commit changes the output for `@Nullable` properties as per OAS 3.0:
```
ParentSchema:
type: object
properties:
child:
nullable: true
oneOf:
- $ref: '#/components/schemas/ChildSchema'
```
Second commit sets `nullable: true` for `Optional<>` fields. I felt like this was desirable, but I can strip that commit if not.
I believe both commits are breaking changes.
Fixes #605

Change nullable handling

---

docs-examples/example-java/build.gradle
gradle/libs.versions.toml
openapi/build.gradle
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaWithNotNullSpec.groovy

Fixed ignoring javax.validation.constraints.NotNull annotation when using @Schema

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPathParamRegexSpec.groovy

Fixed urls with complex URI Path Variables

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/AnnotationRetentionPolicyTransformerSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOutputYamlSpec.groovy

No need to add line `parameters: []` to swagger yaml when operation without parameters

Remove generating empty parameters array

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/AnnotationRetentionPolicyTransformerSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiApplicationVisitorSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiIncludeVisitorSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationTagsSpec.groovy

Now if you describe your tags inside controller (see tests), and tags not described on OpenAPI level, they are not added to the general list of tags. On the left is what the official swagger plugin generates, on the right - micronaut-openapi. This is the case when tags are described at the operation level (see test)

Fixed lost tags block in openAPI, when tags described on operation level

---

docs-examples/example-kotlin/build.gradle
gradle/libs.versions.toml
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerRequiresVisitorSpec.groovy

Add system property (micronaut.openapi.environments) to set active environments for correct process simple @Requires annotations with condition env={...} and notEnv={...}
Fixes #584

Process @Requires annotation with conditions env and notEnv

---

gradle/libs.versions.toml

We used to declare managed-swagger in the core catalog.  We want to remove this for ease of
maintenance, but this means we would break compatibility as here it's managed-swagger-core.
This PR adds a temporary duplication of the catalog to keep managed-swagger in the catalog here
This can be removed for 4.0.0

Duplicate managed-swagger depenedency for core compatibility

---

gradle/libs.versions.toml
openapi/build.gradle
openapi/src/main/java/io/micronaut/openapi/javadoc/JavadocDescription.java
openapi/src/main/java/io/micronaut/openapi/javadoc/JavadocParser.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
openapi/src/test/groovy/io/micronaut/openapi/javadoc/JavadocParserSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationWithjavadocSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiRecordsSpec.groovy

- Refactor JavadocParser. 
- Add support summary and description blocks in method javadoc.
- Add support html tags which will be convert to markdown
- Add support Operation internal parameters field.
- Fix problem with set style for parameter
- Add read class level javadoc (need to records, kotlin data classes and enums)
Fixes #265

Smarter processing of javadoc comments into OpenAPI documentation

---

gradle.properties
gradle/libs.versions.toml
openapi/build.gradle

Groovy projects need `io.micronaut.openapi:micronaut-openapi` in the
compile classpath for the AST transformations to work (unlike Java/Kotlin,
which have it on the annotation processor scope only).
Fixes #781

Expose libraries required for Groovy projects

---

gradle.properties
openapi/build.gradle
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java
openapi/src/main/java/io/micronaut/openapi/visitor/ContextUtils.java
openapi/src/main/java/io/micronaut/openapi/visitor/EndpointsConfiguration.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerRequiresVisitorSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiIncludeVisitorSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPropsFromEnvSpec.groovy
openapi/src/test/resources/application-local.yml
openapi/src/test/resources/application-local2.yml
openapi/src/test/resources/application.yml

Finally added support standard properties application.yml with environments
Fixes #766 
Fixes #759 
Fixes #166
Merge it after https://github.com/micronaut-projects/micronaut-openapi/pull/791

Environments support

---

src/main/docs/guide/introduction.adoc

Since users who want to convert OpenAPI definition files to code templates are likely to see this documentation page, it makes sense to add a reference to the OpenAPI generator in the page.

Refer to the openapi generator in docs

---

openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiOperationViewRenderSpec.groovy

@graemerocher Sorry, found the same problem with copying theme swagger-ui files. But is fix not crittical, this only affects the use of custom themes in swagger. You can release it with version 4.5.2 when you decide it's time

Fixed copying swagger-ui theme files

---

gradle.properties
gradle/libs.versions.toml
openapi/src/main/java/io/micronaut/openapi/annotation/mappers/OpenAPIManagementAnnotationMapper.java
openapi/src/main/java/io/micronaut/openapi/javadoc/JavadocParser.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java
openapi/src/main/java/io/micronaut/openapi/visitor/EndpointsConfiguration.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiIncludeVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiJacksonVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationWithjavadocSpec.groovy
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPropsFromEnvSpec.groovy

- Removed hard dependency on the micronaut-management library.
- Removed Experimental annotations.
- Micronaut test 3.6.2
- fixed endpoints annotation processing for endpoints. Fixed different behavior endpoints processing for groovy and java.
- Bug with check endpoints paths. Fix work with groovy (Fixed #602)
- Remove empty operation description from final yaml
- Add support kdoc `@property` tag for javadoc-parser
- Allow system properties when micronaut environments disabled
@graemerocher When testing on a real project, I tried to use the OpenAPIDecorator annotation. As a result, I got an error that micronaut-management was not added as a dependency, because there is a use of classes from this library.This PR fixes this issue and minor bugs also.
Along the way, I found 2 bugs in the …

Removed hard dependency on the micronaut-management library. Fixes for groovy and endpoints

---

openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java

UI resources paths must start with slash.

---

gradle.properties
gradle/libs.versions.toml
gradle/license.gradle
openapi/openapi-custom-schema-for-class.properties
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/JAXBElement.java
openapi/src/test/groovy/io/micronaut/openapi/MyJaxbElement.java
openapi/src/test/groovy/io/micronaut/openapi/MyJaxbElement2.java
openapi/src/test/groovy/io/micronaut/openapi/MyJaxbElement3.java
openapi/src/test/groovy/io/micronaut/openapi/ObjectId.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenapiCustomSchemaSpec.groovy
openapi/src/test/resources/application-schemaforclass.yml
src/main/docs/guide/customSerializers.adoc
src/main/docs/guide/toc.yml

Now you can set custom classes to create different open api schemas for selected classes:
```yaml
micronaut:
openapi:
schema:
org.somepackage.MyComplexType: java.lang.String
org.somepackage.MyComplexType2: java.lang.Integer
```
or by system properties:
```
-Dmicronaut.opemapi.schema.org.somepackage.MyComplexType=java.lang.String -Dmicronaut.opemapi.schema.org.somepackage.MyComplexType2=java.lang.Integer
```
or by `openapi.properties`
```properties
micronaut.opemapi.schema.org.somepackage.MyComplexType=java.lang.String
micronaut.opemapi.schema.org.somepackage.MyComplexType2=java.lang.Integer
```
Also It can be used for replace classes schema with generics, for example, if you use jaxb generated classes and have custom serializer for JAXBElement class (see tests). And you can set cutom …

Add ability to customize classes schemas in properties.

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
openapi/src/main/java/io/micronaut/openapi/visitor/VisibilityLevel.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPublicFieldsSpec.groovy

I ran into a problem: I have classes that have fields starting with a capital letter (this is a legacy api that needs to be translated to a new engine with backwards compatibility). Okay, the problem can be solved with the JacksonProperty annotation, but when you have several hundred fields, it's very difficult.
My solution is this: I describe the fields in the classes in the same way as they are serialized in json, but in order to have less code, I use the scope for the fields - package-private (otherwise you will have to write the word `public` too many times). I did not add getters or setters to reduce the number of lines, and even lombok will not help here, because there will be a conflict in the names of getters and setters due to the fact that the fields start with a capital letter. …

Add ability to set visibility level for class fields

---

openapi/openapi-schema-decorators.properties
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/api/v1_0_0/MyDto.java
openapi/src/test/groovy/io/micronaut/openapi/api/v2_0_1/MyDto.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaDecoratorSpec.groovy
openapi/src/test/resources/application-schemadecorator.yml
src/main/docs/guide/schemaDecorators.adoc
src/main/docs/guide/toc.yml

If you have some classes with same names in different packages you can set postfix like this:
```yaml
micronaut:
openapi:
schema-postfix:
org.api.v1_0_0: 1_0_0
org.api.v2_0_0: 2_0_0
```
or by system properties:
```
-Dmicronaut.openapi.schema-postfix.org.api.v1_0_0=1_0_0 -Dmicronaut.openapi.schema-postfix.org.api.v2_0_0=2_0_0
```
or by openapi.properties
```properties
micronaut.openapi.schema-postfix.org.api.v1_0_0=1_0_0
micronaut.openapi.schema-postfix.org.api.v2_0_0=2_0_0
```

New feature: schema decorators

---

gradle.properties
gradle/libs.versions.toml
openapi/build.gradle
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPageSpec.groovy

Fix logic for `micronaut.environment.enabled`.
Improve process logic to resolve placeholders.
Fix read system properties, when environments disabled.
Micronaut 3.8.0
Fixes #854

Fix logic for `micronaut.environment.enabled`

---

buildSrc/src/main/groovy/io.micronaut.build.internal.openapi-module.gradle
gradle/libs.versions.toml
openapi-bom/build.gradle
openapi/build.gradle
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/TypeElementUtils.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiNullableTypesSpec.groovy

Fixed process nullable annotations

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEnumSpec.groovy

Don't need to create schemas and process them for classes `java.lang.Object` and `java.lang.Enum`

Add getting schema type from JsonValue method and fixed incorrect processing supertypes for enums

---

openapi/src/main/java/io/micronaut/openapi/visitor/package-info.java

This PR changes the package `io.micronaut.openapi.visitor` to be internal. 
There were breaking changes: 
```
Constructor io.micronaut.openapi.visitor.OpenApiControllerVisitor(java.util.List,java.util.List): Is not binary compatible. 
If you did this intentionally, please accept the change and provide an explanation: [Accept this change](file:///Users/sdelamo/github/micronaut-projects/micronaut-openapi/openapi/build/reports/binary-compatibility-openapi.html#accept-io_micronaut_openapi_visitor_OpenApiControllerVisitorConstructor_io_micronaut_openapi_visitor_OpenApiControllerVisitor_java_util_List_java_util_List_)
Constructor has been removed
```

ci: make visitor package internal

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

Add support requiredMode

---

gradle.properties
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaInheritanceSpec.groovy

- Changed `context.fail` to `context.warn` when path variable is not found (!critical because now if pathVariable is not found the build will fail)
- Fix duplicates references in allOf block
- Sorting schemas in allOf block: schemas with ref must be first

Minor fixes for allOf and other improvements.

---

openapi-generator/build.gradle
openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientCodegen.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerCodegen.java

Without this, it isn't possible for 3rd parties to implement their own code generator.

Make abstract code generator public

---

build-logic/src/main/groovy/io.micronaut.build.internal.openapi-generator-test-suite.gradle
build-logic/src/main/groovy/io/micronaut/build/internal/openapi/OpenApiGeneratorTask.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorOptionsBuilder.java
openapi-generator/src/main/resources/templates/java-micronaut/common/operationAnnotations.mustache
test-suite-generator-util/src/main/java/io/micronaut/openapi/testsuite/GeneratorMain.java
test-suite-server-generator/build.gradle
test-suite-server-generator/spec.yaml
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/api/ParametersController.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/api/ResponseBodyController.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/dated/DatedResponse.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/dated/DatedResponseBodyWriter.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/filter/MyFilter.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/filter/MyFilterBinder.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/page/PageBodyWriter.java
test-suite-server-generator/src/test/groovy/io/micronaut/openapi/test/api/ParametersControllerSpec.groovy
test-suite-server-generator/src/test/groovy/io/micronaut/openapi/test/api/ResponseBodyControllerSpec.groovy

These changes are to allow the use of custom types for parameters and response bodies to utilize all Micronaut capabilities for code simplification.
As an example, if we add the following parameter mappings:
```js
[
{name: "page", location: "QUERY", mappedType: "io.micronaut.data.model.Pageable"},
{name: "size", location: "QUERY", mappedType: "io.micronaut.data.model.Pageable"},
{name: "sortOrder", location: "QUERY", mappedType: "io.micronaut.data.model.Pageable"},
]
```
micronaut `Pageable` will be used for `page`, `size` or `sortOrder` headers:
```java
@Get("/sendPageQuery")
@Produces({"application/json"})
Mono<String> sendPageQuery(
@NotNull
Pageable pageable
);
```
instead of each header being a separate parameter:
```java
@Get("/sendPageQuery")
@Produces({"application/json"}) …
```

Add parameter and response body mapping

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiGroupInfoVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiJsonViewSpec.groovy

Add support for @JsonView

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaGenericsSpec.groovy

Add process WildcardElement and GenericPlaceholderElement (4.10)

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerGroovySpec.groovy

Fixed cannot generate schema for response having a collection of enums (Groovy)

---

gradle/libs.versions.toml
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
src/main/docs/guide/customSerializers.adoc
src/main/docs/guide/exposingSwaggerOutput.adoc
src/main/docs/guide/kotlin.adoc
src/main/docs/guide/openApiViews/mappingPath.adoc
src/main/docs/guide/openApiViews/rapidoc.adoc
src/main/docs/guide/openApiViews/redoc.adoc
src/main/docs/guide/openApiViews/swaggerui.adoc
src/main/docs/guide/openApiViews/swaggerui/oauth2.adoc
src/main/docs/guide/schemaDecorators.adoc
src/main/docs/guide/toc.yml
src/main/docs/guide/versionsAndGroups/groups.adoc
src/main/docs/guide/versionsAndGroups/versions.adoc

Add ability to set project directory.

---

openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientCodegen.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerCodegen.java
openapi-generator/src/main/resources/templates/java-micronaut/common/model/jackson_annotations.mustache
openapi-generator/src/main/resources/templates/java-micronaut/common/model/model.mustache
openapi-generator/src/main/resources/templates/java-micronaut/common/model/pojo.mustache
openapi-generator/src/main/resources/templates/java-micronaut/common/params/validation.mustache
openapi-generator/src/test/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPointTest.java

Fix readonly properties for generator.

---

openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiDuplicteElementsSpec.groovy

Remove duplicate elements from final OpenApi object.

---

docs-examples/example-kotlin/build.gradle
gradle.properties
gradle/libs.versions.toml
openapi-generator/build.gradle
openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
openapi-generator/src/test/java/io/micronaut/openapi/generator/AbstractMicronautCodegenTest.java
openapi-generator/src/test/java/io/micronaut/openapi/generator/MicronautServerCodegenTest.java
openapi/build.gradle
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/ConfigUtils.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
src/main/docs/guide/kotlin.adoc
test-suite-generator-util/src/main/java/io/micronaut/openapi/testsuite/GeneratorMain.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/api/ParametersController.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/api/RequestBodyController.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/api/ResponseBodyController.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/dated/DatedResponseBodyWriter.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/filter/MyFilter.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/filter/MyFilterBinder.java
test-suite-server-generator/src/main/java/io/micronaut/openapi/test/page/PageBodyWriter.java
test-suite-server-generator/src/test/groovy/io/micronaut/openapi/test/api/ResponseBodyControllerSpec.groovy

Update libraries.
Removed redundant dependencies.
Update commons-codec to remove vulnerability

Openapi generator 7.0.1

---

openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java

Setting generateHttpResponseWhereRequired option does not work because it is not passed to codeGenerator.

Fix setting generateHttpResponseWhereRequired option

---

openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java

Added lost http methods

---

openapi/src/main/java/io/micronaut/openapi/visitor/ConfigUtils.java

Group properties such as `micronaut.openapi.groups.*.packages=***` are not being read from the `openapi.properties` file, and therefore the properties are not being respected. The `readGroupsProperties` function passes the property name, to `setGroupProperty` but it is currently passing the full name, i.e. `micronaut.openapi.groups.*.packages`, when it should just be passing the key after the group name, i.e. `packages`. 
Fixes #1267

fix group properties not being read from openapi.properties

---

gradle.properties
openapi/openapi-custom-schema-for-iterable-class.properties
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
openapi/src/test/groovy/io/micronaut/openapi/SwaggerPage.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenapiCustomSchemaSpec.groovy

Fixed https://github.com/micronaut-projects/micronaut-openapi/issues/1276

isArray and isIterable should be done after checking customTypeSchema. (5.2.x)

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenapiCustomSchemaSpec.groovy

Generic update derived from #1276 
```kotlin
@Get("{?pageable*}")
@ApiResponse(responseCode = "200")
suspend fun hello(pageable: Pageable): Page<String> = Page.of(listOf("Hello, World!"), pageable, 2)
interface SwaggerPage<T> {
@get:Schema(description = "The content.") val content: List<T>
@get:Schema(description = "The pageable for this slice.") val pageable: Pageable
}
```
Current the items type was `object`, which was lost the generic type
```yml
content:
type: array
description: The content.
items:
type: object
```
Expected it should be inherit the generic type if it had generics
```
content:
type: array
description: The content.
items:
type: string
```

Custom serializers should inherit generic types

---

openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiOperationViewRenderSpec.groovy

Add missing apostrophe for `urls` property of `SwaggerUIBundle` in `SwaggerUiConfig` to fix #1321 .

Fix "Invalid Swagger UI index.html for versioned API" #1321

---

openapi/src/main/java/io/micronaut/openapi/view/OpenApiExplorerConfig.java

Fixes #1411 
After reviewing the `openapi-explorer` documentation [Hide/Show Sections](https://github.com/Authress-Engineering/openapi-explorer/blob/release/2.1/docs/documentation.md#hideshow-sections), I identified a missing character in the `hide-components` option.
After applying the fix, I successfully ran the application locally and confirmed that the expected behavior of hiding the Components section was achieved:

Fix typo on OpenAPI explorer hide-components option

---

build-logic/src/main/groovy/io.micronaut.build.internal.openapi-kotlin-kapt-generator-test-suite.gradle
build-logic/src/main/groovy/io.micronaut.build.internal.openapi-kotlin-ksp-generator-test-suite.gradle
build-logic/src/main/groovy/io/micronaut/build/internal/openapi/OpenApiGeneratorTask.java
gradle.properties
openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegen.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautClientOptionsBuilder.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegen.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautServerOptionsBuilder.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
openapi-generator/src/main/resources/templates/kotlin-micronaut/common/model/field_annotations.mustache
openapi-generator/src/main/resources/templates/kotlin-micronaut/common/model/jackson_annotations.mustache
openapi-generator/src/main/resources/templates/kotlin-micronaut/common/params/validation_field.mustache
test-suite-generator-util/src/main/java/io/micronaut/openapi/testsuite/GeneratorMain.java
test-suite-kotlin-kapt-client-generator/build.gradle
test-suite-kotlin-kapt-server-generator/build.gradle
test-suite-kotlin-ksp-client-generator/build.gradle
test-suite-kotlin-ksp-client-generator/petstore.json
test-suite-kotlin-ksp-server-generator/build.gradle
test-suite-kotlin-ksp-server-generator/spec.yaml

It means without prefix `@field:` for annotaions on constructor parameters level

Add ksp flag to kotlin generator to generate only KSP compatible classes

---

gradle/libs.versions.toml
openapi-annotations/src/main/java/io/micronaut/openapi/annotation/OpenAPIGroupInfo.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiGroupInfoVisitor.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiGroupSpec.groovy

Add ability to set custom SecuritytSchemes to OpenApiGroup

---

openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerGroovySpec.groovy

Fix conversion annotations with groovy

---

build-logic/src/main/groovy/io.micronaut.build.internal.openapi-test-java.gradle
gradle/libs.versions.toml
settings.gradle
test-suite-java-jaxrs/build.gradle.kts
test-suite-java-jaxrs/src/test/java/io/micronaut/open/jaxrs/Application.java
test-suite-java-jaxrs/src/test/java/io/micronaut/open/jaxrs/OpenApiExposedTest.java
test-suite-java-jaxrs/src/test/java/io/micronaut/open/jaxrs/OpenApiGeneratedTest.java
test-suite-java-jaxrs/src/test/java/io/micronaut/open/jaxrs/TestController.java
test-suite-java-jaxrs/src/test/java/io/micronaut/open/jaxrs/TestControllerTest.java
test-suite-java-jaxrs/src/test/resources/application.properties
test-suite-java-jaxrs/src/test/resources/logback.xml

see: https://github.com/micronaut-projects/micronaut-core/issues/4983

test: JaxRS Test

---

openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
openapi-generator/src/main/resources/templates/java-micronaut/common/model/enum.mustache
openapi-generator/src/main/resources/templates/java-micronaut/common/model/model.mustache
openapi-generator/src/main/resources/templates/kotlin-micronaut/common/model/enum.mustache
openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
openapi-generator/src/test/resources/3_0/enum.yml

Add support non string values in kotlin enums.
Fixed #1449

Fix generating non string enums.

---

build-logic/src/main/groovy/io.micronaut.build.internal.openapi-java-generator-test-suite.gradle
build-logic/src/main/groovy/io.micronaut.build.internal.openapi-kotlin-kapt-generator-test-suite.gradle
build-logic/src/main/groovy/io.micronaut.build.internal.openapi-kotlin-ksp-generator-test-suite.gradle
build-logic/src/main/groovy/io/micronaut/build/internal/openapi/OpenApiGeneratorTask.java
openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
test-suite-generator-util/src/main/java/io/micronaut/openapi/testsuite/GeneratorMain.java
test-suite-java-client-generator/build.gradle
test-suite-java-client-generator/src/test/groovy/io/micronaut/openapi/test/api/ClientSpec.groovy
test-suite-java-client-generator/src/test/java/io/micronaut/openapi/test/util/TestUtils.java
test-suite-java-server-generator/build.gradle
test-suite-java-server-generator/src/test/resources/application-test.properties
test-suite-java-server-generator/src/test/resources/application-test.yml
test-suite-kotlin-kapt-client-generator/build.gradle
test-suite-kotlin-kapt-client-generator/src/test/groovy/io/micronaut/openapi/test/api/ClientSpec.groovy
test-suite-kotlin-kapt-client-generator/src/test/java/io/micronaut/openapi/test/util/TestUtils.java
test-suite-kotlin-kapt-client-generator/src/test/kotlin/io/micronaut/openapi/test/api/ClientTest.kt
test-suite-kotlin-kapt-server-generator/build.gradle
test-suite-kotlin-kapt-server-generator/src/test/resources/application-test.properties
test-suite-kotlin-kapt-server-generator/src/test/resources/application-test.yml
test-suite-kotlin-ksp-client-generator/build.gradle
test-suite-kotlin-ksp-client-generator/src/test/groovy/io/micronaut/openapi/test/api/ClientSpec.groovy
test-suite-kotlin-ksp-client-generator/src/test/java/io/micronaut/openapi/test/util/TestUtils.java
test-suite-kotlin-ksp-client-generator/src/test/kotlin/io/micronaut/openapi/test/api/ClientTest.kt
test-suite-kotlin-ksp-server-generator/build.gradle
test-suite-kotlin-ksp-server-generator/src/test/resources/application-test.properties
test-suite-kotlin-ksp-server-generator/src/test/resources/application-test.yml

See https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/949

Fix mapping entry point generator properties to client properties

---

openapi-annotations/src/main/java/io/micronaut/openapi/annotation/OpenAPIGroup.java
openapi-annotations/src/main/java/io/micronaut/openapi/annotation/OpenAPIGroups.java
openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
openapi/src/main/java/io/micronaut/openapi/visitor/group/EndpointGroupInfo.java
openapi/src/main/java/io/micronaut/openapi/visitor/group/EndpointInfo.java
openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiGroupSpec.groovy

Add ability to set group specific operation extensions.
