- .travis.yml
- config/checkstyle/checkstyle.xml
- openapi/build.gradle
- openapi/src/main/java/io/micronaut/openapi/util/Yaml.java
- travis-build.sh
* Removed jdk11
* Publish docs for 1.1.x
> Updated travis-build.sh

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
Fixes micronaut-projects/micronaut-core#930
> Fixes micronaut-projects/micronaut-core#930

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationParseSpec.groovy
* Fix to pick name property from @Schema annotation on field level for generated swagger yml
> #4 Read property name from @Schema

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
Fixes https://github.com/micronaut-projects/micronaut-openapi/issues/32
> Add mapping for @PathVariable

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiParameterMappingSpec.groovy
> Do not generate request body if all parameters are ignored

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
Micronaut says that it supports io.reactivex.Observable
In that case, the response will be an array of elements
> Observable should return an array of elements

- src/main/docs/guide/gettingStarted.adoc
See the proposed documentation enhancement at https://github.com/micronaut-projects/micronaut-core/issues/1844
> Add location for generated YML file for Kotlin

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPublicFieldsSpec.groovy
Currently the `required` list of schema is always empty
> Populates required list for schema

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
section `required` wasn't being added to Schema object. It's a fix for that
> Fixed required properties for a Schema

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPublicFieldsSpec.groovy
> Fix fields defaults to not required

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiComplexSchemaSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiInheritedPojoControllerSpec.groovy
#63 Support complex schema and discriminator
* anyOf, oneOf, and allOf support in responses.
* support for discriminator field and discriminator mapping.
> Support complex schema and discriminator

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationParseSpec.groovy
Fixes https://github.com/micronaut-projects/micronaut-openapi/issues/11
> Fix processing of SecurityRequirement when using in Operation.

- src/main/docs/guide/openApiViews.adoc
https://github.com/micronaut-projects/micronaut-openapi/issues/108
> Added example for "Gradle for Kotlin projects"

- openapi/src/main/java/io/micronaut/openapi/util/Yaml.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiDateTimeExampleSchemaSpec.groovy
https://github.com/micronaut-projects/micronaut-openapi/issues/124
> Issue #124 - add JavaTimeModule

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
Try to find project dir for user defined target file ('micronaut.openapi.target.file') and
additional openapi files ('micronaut.openapi.additional.files') when the provided path is not absolute.
Add null check on Path.getParent.
Currently with
```
tasks.withType(JavaCompile){
options.fork = true
options.encoding = 'UTF-8'
// for micronaut, it keeps the parameters' name
options.compilerArgs << '-parameters'
options.forkOptions.jvmArgs << '-Dmicronaut.openapi.target.file=toto.yml'
options.forkOptions.jvmArgs << '-Dmicronaut.openapi.views.spec=redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop'
}
```
I have:
```
Note: Generating OpenAPI Documentation
Note: Writing OpenAPI YAML to destination: toto.yml
Application.java:19: warning: Unable to generate …
```
> Refactor open api spec file dump.

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
Enable
https://github.com/micronaut-projects/micronaut-core/pull/2702/
to get annotation processor supported options.
> Declare @SupportedOptions for OpenApiApplicationVisitor

- openapi/src/main/java/io/micronaut/openapi/view/AbstractViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RedocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/Renderer.java
- openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/main/resources/templates/rapidoc/index.html
- openapi/src/main/resources/templates/redoc/index.html
- openapi/src/main/resources/templates/swagger-ui/index.html
- openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiViewParseSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiViewRenderSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationHeadersSpec.groovy
- src/main/docs/guide/openApiViews.adoc
- src/main/docs/guide/systemProperties.adoc
- src/main/docs/guide/toc.yml
possibility to speficy these options in a configuration file.
> Add more options for openapi views and

- openapi/src/main/java/io/micronaut/openapi/util/YAMLFactory.java
- openapi/src/main/java/io/micronaut/openapi/util/Yaml.java
- openapi/src/main/java/io/micronaut/openapi/view/AbstractViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapiPDFConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RedocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/main/resources/templates/redoc/index.html
- openapi/src/main/resources/templates/swagger-ui/index.html
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiArraySchemaSpec.groovy
- src/main/docs/guide/openApiViews.adoc
- documentation
- remove spec-url from valid options
- add style (css) as valid option.
- add RapiPdf to all renderers
- fix some warnings
- Handle @ArraySchema with arraySchema field.
> Minor fixes:

- openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
https://github.com/mrin9/RapiDoc/commit/672a1009d2462d6785b7e4534392d86242f3e204
> Remove deprecated rapidoc attribute.

- openapi/src/main/java/io/micronaut/openapi/javadoc/JavadocParser.java
- openapi/src/test/groovy/io/micronaut/openapi/javadoc/JavadocParserSpec.groovy
May fix https://github.com/micronaut-projects/micronaut-openapi/issues/129
> Do not append '\n' for param name.

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
process @Body annotation when necessary.
> Fix for Issue #157

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
https://github.com/micronaut-projects/micronaut-openapi/issues/161
> fix: Issue #161 - check if enum is null

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- src/main/docs/guide/configuration.adoc
- src/main/docs/guide/openApiViews.adoc
Adds the ablility to prepend paths with a user defined server context path,
and to expand user defined properties in open api text fields.
> Prepend paths with context server path and expand properties

- openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
> add new rapidoc option nav-item-spacing

- openapi/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElementExt.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiBasicSchemaSpec.groovy
https://github.com/micronaut-projects/micronaut-openapi/issues/19
> Issue #19 - Support fluent accessors

- openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
> Add new rapidoc options

- openapi/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElementExt.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
https://github.com/micronaut-projects/micronaut-openapi/issues/127
and also do not make micronaut-inject-java required for groovy.
> Fix #127 - Filter out metaClass field.

- openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
https://github.com/mrin9/RapiDoc/pull/196/files
> Fix RapiDoc attribute name.

- .github/dependabot.yml
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
> enable Dependabot 2

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
Happens with micronaut 2.0.
See https://github.com/micronaut-projects/micronaut-core/issues/3575
> Avoid to write multiple times the spec and view files.

- src/main/docs/guide/openApiViews.adoc
Not sure if important but docs were missing info about Groovy+Gradle projects on how to generate views
> Groovy docs missing for views

- openapi/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElementExt.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaGenericsSpec.groovy
Use different method to find fields and methods.
> Issue #279 - Refactored getBeanProperties

- build.gradle
- openapi/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElementExt.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
https://github.com/micronaut-projects/micronaut-openapi/issues/297
Difficult to test because micronaut-openapi depends on an old version of micronaut-core
> Issue-297 - Parameters of type Session or those annotated with @SessionValue should be ignored

- gradle/wrapper/gradle-wrapper.properties
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileUploadSpec.groovy
> Issue #303 - multiple content types in separate methods

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiComplexSchemaSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiJsonUnwrappedsSpec.groovy
Fixes https://github.com/micronaut-projects/micronaut-openapi/issues/319
> Support Jackson's @JsonNaming and @JsonProperty

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiParameterMappingSpec.groovy
+ Refactoring
Fixes https://github.com/micronaut-projects/micronaut-openapi/issues/318
> Include extra parameters into request's body

- openapi/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElementExt.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiInterfaceBeanSpec.groovy
Fixes https://github.com/micronaut-projects/micronaut-openapi/issues/288
> Support abstract types with get/set properties

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
Fixes https://github.com/micronaut-projects/micronaut-openapi/issues/343
> Fix media type processing

- src/main/docs/guide/cli.adoc
> Fix openapi feature name in the CLI

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
Fixed issue #302.
I was trying to add test. Should the functionality be that `nullable: false` to the generated schema?
If needed, I will make the required modifications.
> Checking Nonnull annotation for Kotlin compatibility

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiExtensionSpec.groovy
> Handle @Extension without name

- src/main/docs/guide/gettingStarted.adoc
- src/main/docs/guide/openApiDefinition.adoc
- src/main/docs/guide/toc.yml
This extracts `@OpenApiDefinition` to its own section in the documentation
> doc: Extract OpenAPI Definition

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOutputYamlSpec.groovy
This hopefully fixes ordering issue and also https://github.com/micronaut-projects/micronaut-openapi/issues/467.
It fixes order for Paths and all Components. Is there maybe any other case where some element that should be handled?
> Fix order of paths and schemas again

- src/main/docs/guide/configuration/propertiesFileConfiguration.adoc
> fixed a typo in the documentaion

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiParameterMappingSpec.groovy
Fixes #416
According to the javadoc, "the annotation may be used (...) at method
level to add a parameter to the operation, even if not bound to any
method parameter".
This commit adds support for that.
> Process Swagger `@Parameter` annotation on methods

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/AnnotationRetentionPolicyTransformerSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiApplicationVisitorSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiIncludeVisitorSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiMergeSchemaSpec.groovy
Fixes #522
This PR modifies some of the existing tests just to add missing tests, but it's not a breaking change.
> Process the `@Server` annotation

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/SchemaMetaAnnotationSpec.groovy
> Process UUID fields properly

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
> Non nullable fields are required in generated openapi spec

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
> Do not use JavaClassElementExt and JavaClassElement.

- openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
> Use quoted string for some Swagger-UI properties

- src/main/docs/guide/openApiViews/viewsGenerationWithSystemProperties.adoc
> Fix docs about how to generate html views with Maven

- openapi/openapi-custom-endpoints.properties
- openapi/src/main/java/io/micronaut/openapi/visitor/EndpointsConfiguration.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEndpointVisitorSpec.groovy
> Process custom endpoints.path properly

- docs-examples/example-groovy/build.gradle
- docs-examples/example-groovy/src/test/groovy/io/micronaut/configuration/openapi/docs/controllers/HelloController.groovy
- docs-examples/example-groovy/src/test/groovy/io/micronaut/configuration/openapi/docs/controllers/annotations/HelloController.groovy
- docs-examples/example-java/build.gradle
- docs-examples/example-java/src/test/java/io/micronaut/configuration/openapi/docs/controllers/HelloController.java
- docs-examples/example-java/src/test/java/io/micronaut/configuration/openapi/docs/controllers/annotations/HelloController.java
- docs-examples/example-kotlin/build.gradle
- docs-examples/example-kotlin/src/test/kotlin/io/micronaut/configuration/openapi/docs/controllers/HelloController.kt
- docs-examples/example-kotlin/src/test/kotlin/io/micronaut/configuration/openapi/docs/controllers/annotations/HelloController.kt
- gradle.properties
- openapi/build.gradle
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
This PR is sent separated to address #577.
> Upgrade to Micronaut 3

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
> Do not create requestBody with only path parameters

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiReturnVoidSpec.groovy
> Handle Void return types

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSecurityRequirementSpec.groovy
> Add 'name' key when using `@SecurityScheme`

- gradle.properties
- openapi/build.gradle
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
> Handle RxJava3 types

- gradle.properties
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationParseSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
- src/main/docs/guide/breaks.adoc
- src/main/docs/guide/toc.yml
> `@ApiResponse` always takes precedence over other annotations

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileUploadBodyParameterSpec.groovy
> Use `@Part` value as parameter name

- gradle.properties
. [githubCoreBranch=3.5.x](https://github.com/micronaut-projects/micronaut-openapi/commit/250a428298ff595935b64843847fd4578a49e596)
- [groovy to 3.0.10](https://github.com/micronaut-projects/micronaut-openapi/commit/f0fd94937300a17998daad58868c39a3e5eecf27)
- [micronaut test to 3.2.0](https://github.com/micronaut-projects/micronaut-openapi/commit/2ba17ab823135b8704a6f1a1e930a3e6b558d8ab)
> ci: project version to 4.1.0-SNAPSHOT

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiHttpHeadersSpec.groovy
classes for parameters
Fixed #664
> Add io.micronaut.http.HttpHeaders class to ignore

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEmptyBodyResponseSpec.groovy
> Fixed wrong content block, when response without content

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiParameterSchemaSpec.groovy
> Fixed problem with internal @Parameter parameters

- openapi/src/main/java/io/micronaut/openapi/postprocessors/JacksonDiscriminatorPostProcessor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiInnerClassSpec.groovy
- src/main/docs/guide/namingstrategy.adoc
> Fixed controller search in inner classes. Added lost property naming strategies.

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEncodingSpec.groovy
See test. Left file generated by official swagger plugin, right - by micronaut-openapi
> Fixed encoding style parameter. Fix lost schema ref

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiApplicationVisitorSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSecurityRequirementSpec.groovy
Fix lost properties in SecurityScheme. Improve test for SecurityScheme. 
Fix lost default value.
About bug: left file generated by swagger plugin, right - micronaut-openapi. This PR fixed this issue
> Fix lost properties in SecurityScheme. Improve test for SecurityScheme.

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEncodingSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiExternalDocsSpec.groovy
Added support ExternalDocumentation annotation, improved test for complex  Content block
> Added support ExternalDocumentation annotation

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
> Fix NPE when components or schemas are empty, but use property.name.strategy property

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiIncludeVisitor.java
Fixed #693
PS I tested it locally - all works fine with groovy with this fix
> Enable OpenApiIncludeVisitor for groovy projects

- gradle/libs.versions.toml
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiParameterMappingSpec.groovy
- Swagger 2.2.2
- Add support Body annotation with member value.
- Add processing Body parameter annotations.
- Minor code cosmetics
Fixed #774
> Add support Body annotation with member value. Fixes #774

- openapi/src/main/java/io/micronaut/openapi/view/AbstractViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapiPDFConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RedocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
- openapi/src/main/resources/templates/swagger-ui/oauth2-redirect.html
Actualization redoc/rapidoc/swagger-ui config properties.
Move from `https://github.com/ostranme/swagger-ui-themes` to `https://github.com/ilyamixaltik/swagger-themes`
> Actualization redoc/rapidoc/swagger-ui config properties

- gradle.properties
- openapi/src/main/java/io/micronaut/openapi/view/AbstractViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapiPDFConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RedocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiOperationViewRenderSpec.groovy
Fixed incorrect logic for copy UI resources from micronaut-openapi jar file.
Add checks for empty javadocs.
> Fixed incorrect logic for copy UI resources from micronaut-openapi jar file.

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiBasicSchemaSpec.groovy
> Improve processing openapi types and formats

- gradle.properties
- gradle/libs.versions.toml
Fixed problem with groovy: were duplicated properties with inheritance in openapi schema. problem was in core module (see https://github.com/micronaut-projects/micronaut-core/pull/8084)
Fixed #670
> Fixed problem with duplicated properties from inheritance (groovy). Swagger 2.2.3

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiApplicationVisitorSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSecurityRequirementSpec.groovy
Improve processing SecuritySchemes. 
Fixed bug with name property.
Fixed process security schemes with type DEFAULT, when set only ref property.
Fixed #811
Fixed #653
> Improve processing SecuritySchemes. Fixed bug with name property.

- openapi/src/main/java/io/micronaut/openapi/view/AbstractViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapiPDFConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RedocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/Renderer.java
- openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiOperationViewRenderSpec.groovy
Added ability to customize ui resources context path. Added support for micronaut.server.context-path property
Fixes #823
> Added ability to customize ui resources context path. Added support for micronaut.server.context-path property

- openapi/src/main/java/io/micronaut/openapi/swagger/ObjectMapperFactory.java
- openapi/src/main/java/io/micronaut/openapi/swagger/PrimitiveType.java
- openapi/src/main/java/io/micronaut/openapi/swagger/jackson/util/ModelDeserializer.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiIncludeVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEnumSpec.groovy
> Add support Hidden, JsonIgnore annotations for enum values

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy
Now you don't need to specify mediaType for each response . By default, values are taken from produces, but it remains possible to override this mediaType in the ApiResponse.Content block
> Improvement process ApiResponse media types

- gradle.properties
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiParameterMappingSpec.groovy
Fixed #833
Also added support `@Schema` annotation for endpoint parameters
> Fix @QueryValue for List<String> parameters

- openapi/src/main/java/io/micronaut/openapi/view/AbstractViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/OpenApiViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapiPDFConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RapidocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/RedocConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
- openapi/src/main/resources/templates/rapidoc/index.html
- openapi/src/main/resources/templates/redoc/index.html
- openapi/src/main/resources/templates/swagger-ui/index.html
- openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiOperationViewRenderSpec.groovy
- src/main/docs/guide/openApiViews/rapidoc.adoc
- src/main/docs/guide/openApiViews/rapipdf.adoc
- src/main/docs/guide/openApiViews/redoc.adoc
- src/main/docs/guide/openApiViews/swaggerui.adoc
Fixed #829 by prefixing the JavaScript with the correct paths.
> fix #829 Fix issue with javascript path rendering in views

- gradle.properties
- gradle/libs.versions.toml
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaPrimitiveTypeSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/SchemaMetaAnnotationSpec.groovy
> Added processing Schema attributes, when it used with implementation.

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiJsonUnwrappedsSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiUrlParametersAsPojoSpec.groovy
> Add correct processing exploded QueryValues

- .gitattributes
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiInheritedPojoControllerSpec.groovy
> Changed processing logic for inheritance.

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiInheritedPojoControllerSpec.groovy
Fixed bug with wrong references for schemas with inheritance, when used custom schema name
> Fixed bug with wrong references for schemas with inheritance, when used custom schema name

- .gitattributes
- config/accepted-api-changes.json
- gradle.properties
- gradle/libs.versions.toml
- openapi-bom/build.gradle
- openapi/src/main/java/io/micronaut/openapi/swagger/core/util/ModelDeserializer.java
Actualize libraries versions. Added accepted-api-changes lines. Swagger 2.2.8
> Actualize libraries versions. Added accepted-api-changes lines. Swagger 2.2.8

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
See Issue #894 for an explination.
> Fix ConcurrentModificationException #894

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
> Add processing class level Hidden annotation on Controller

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerRequiresVisitorSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
- src/main/docs/guide/endpoints/endpointstags.adoc
> Fix java.util collections schemas

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileUploadBodyParameterSpec.groovy
> Fix compilation issue with MultipartBody

- .github/workflows/graalvm.yml
- settings.gradle
- src/main/docs/guide/customSerializers.adoc
- src/main/docs/guide/endpoints/enableendpoints.adoc
- src/main/docs/guide/endpoints/endpointspath.adoc
- src/main/docs/guide/endpoints/endpointssecurityrequirements.adoc
- src/main/docs/guide/endpoints/endpointstags.adoc
- src/main/docs/guide/exposingSwaggerOutput.adoc
- src/main/docs/guide/mergingSchemas.adoc
- src/main/docs/guide/openApiViews/mappingPath.adoc
- src/main/docs/guide/openApiViews/rapidoc.adoc
- src/main/docs/guide/openApiViews/redoc.adoc
- src/main/docs/guide/openApiViews/swaggerui.adoc
- src/main/docs/guide/openApiViews/swaggerui/oauth2.adoc
- src/main/docs/guide/schemaDecorators.adoc
> Migrate to new configuration asciidoc macro and build plugin 5.4.x

- openapi/src/main/resources/templates/rapidoc/index.html
> Allow POST requests for rapidoc

- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- openapi/src/main/java/io/micronaut/openapi/swagger/ObjectMapperFactory.java
- openapi/src/main/java/io/micronaut/openapi/swagger/jackson/util/ModelDeserializer.java
- settings.gradle
swagger 2.2.8
jsoup 1.15.4
kotlin 1.8.10
android-annotation 1.6.0
gradle 7.6.1
micronaut 3.8.7
micronaut-test 3.9.1
groovy 3.0.15
> Upgrade libraries

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiRequestBeanSpec.groovy
> Add protection of duplicate parameters

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/test1/Entity.java
- openapi/src/test/groovy/io/micronaut/openapi/test1/EntityWithGeneric.java
- openapi/src/test/groovy/io/micronaut/openapi/test2/Entity.java
- openapi/src/test/groovy/io/micronaut/openapi/test2/EntityWithGeneric.java
- openapi/src/test/groovy/io/micronaut/openapi/test3/Entity.java
- openapi/src/test/groovy/io/micronaut/openapi/test3/EntityWithGeneric.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiBasicSchemaSpec.groovy
> Auto solve problem schema names conflicts for classes with same name, but with different packages.

- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
> Add support `.yaml` additional files

- .github/workflows/gradle.yml
- .github/workflows/release.yml
- gradle.properties
- Micronaut Framework 4.0.0-M1
- Groovy 4.0.10
- Github Actions Sync
> ci: GitHub Action sync and milestones dependencies

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEnumSpec.groovy
> Fix enum schema type

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
> Add logging, if we have problems with getting beanProperties

- gradle.properties
- openapi/src/main/java/io/micronaut/openapi/swagger/jackson/util/ModelDeserializer.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
- openapi/src/main/java/io/micronaut/openapi/visitor/SimpleSchema.java
- openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiComplexSchemaSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileUploadBodyParameterSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiFileUploadSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiInheritedPojoControllerSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPageSpec.groovy
Also added print stacktrace and exception message when we have a problem.
Fixes #963
> Remove type 'object' from allOf property.

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiIncludeVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiJacksonVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/Utils.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiApplicationVisitorSpec.groovy
> Add ability to disable micronaut-openapi

- src/main/docs/guide/customSerializers.adoc
> fixed single character issue in customSerializers.adoc

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiParameterMappingSpec.groovy
Also fix process empty list default value like this `@QueryValue(defaultValue = ",") List<String> items`
> Fix parse default enum value

- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorOptionsBuilder.java
- openapi-generator/src/main/resources/templates/java-micronaut/client/api.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/jackson_annotations.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/pojo.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/server/params/type.mustache
- openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenSerializationLibraryTest.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/MicronautServerCodegenTest.java
- test-suite-server-generator/spec.yaml
- test-suite-server-generator/src/main/java/io/micronaut/openapi/test/api/ParametersController.java
- test-suite-server-generator/src/main/java/io/micronaut/openapi/test/api/RequestBodyController.java
- test-suite-server-generator/src/main/java/io/micronaut/openapi/test/api/ResponseBodyController.java
- test-suite-server-generator/src/test/groovy/io/micronaut/openapi/test/api/ParametersControllerSpec.groovy
- test-suite-server-generator/src/test/groovy/io/micronaut/openapi/test/api/RequestBodyControllerSpec.groovy
- test-suite-server-generator/src/test/groovy/io/micronaut/openapi/test/api/ResponseBodyControllerSpec.groovy
Improvements for:
* Date time types
* File types
* formatting
> Generator improvements

- openapi/build.gradle
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
> Fixes SLF4J initializing

- ISSUE_TEMPLATE.md
- MAINTAINING.md
- README.md
- gradle.properties
- gradle/libs.versions.toml
- src/main/docs/guide/cli.adoc
- src/main/docs/guide/configuration/propertiesFileConfiguration.adoc
- src/main/docs/guide/configuration/systemPropertyConfiguration.adoc
- src/main/docs/guide/customSerializers.adoc
- src/main/docs/guide/endpoints/endpointservers.adoc
- src/main/docs/guide/endpoints/endpointspath.adoc
- src/main/docs/guide/endpoints/endpointssecurityrequirements.adoc
- src/main/docs/guide/endpoints/endpointstags.adoc
- src/main/docs/guide/endpoints/micronautendpoints.adoc
- src/main/docs/guide/exposingSwaggerOutput.adoc
- src/main/docs/guide/gettingStarted.adoc
- src/main/docs/guide/openApiViews/mappingPath.adoc
- src/main/docs/guide/openApiViews/rapidoc.adoc
- src/main/docs/guide/openApiViews/redoc.adoc
- src/main/docs/guide/openApiViews/swaggerui.adoc
- src/main/docs/guide/openApiViews/swaggerui/oauth2.adoc
- src/main/docs/guide/openApiViews/viewsGenerationWithPropertiesFile.adoc
- src/main/docs/guide/openApiViews/viewsGenerationWithSystemProperties.adoc
- src/main/docs/guide/schemaDecorators.adoc
- src/main/docs/guide/serverContext/serverFilter.adoc
- src/main/docs/guide/swaggerAnnotations/schemasAndGenerics.adoc
- src/main/docs/guide/swaggerAnnotations/schemasAndMetaAnnotations.adoc
- src/main/docs/guide/swaggerAnnotations/schemasAndPojos.adoc
- src/main/docs/guide/swaggerAnnotations/schemasNaming.adoc
Also added note about `-parameters` flag
Fixed #773
> Update libraries. Minor documentation fixes

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaGenericsSpec.groovy
> Add process WildcardElement and GenericPlaceholderElement

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiJsonViewSpec.groovy
The same feature as here: https://github.com/swagger-api/swagger-core/commit/f050d0a63c5992c991ad066b15867c32ae6ded1a
To support jackson `MapperFeature.DEFAULT_VIEW_INCLUSION`
> Add ability to change JsonView default inclusion

- openapi/openapi-placeholders.properties
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiApplicationVisitorSpec.groovy
> Fixes replace placeholders

- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/enum.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/model.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/pojo.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/common/params/validation.mustache
> Fix readonly properties.

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiBasicSchemaSpec.groovy
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerGroovySpec.groovy
> element.getValue(..., String.class) -> element.stringValue(...)

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiMapSchemaSpec.groovy
Solve the issue of type=object being removed for MapSchema properties.
> Fixes #1175

- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/pojo.mustache
- openapi-generator/src/test/java/io/micronaut/openapi/generator/MicronautClientCodegenTest.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/MicronautServerCodegenTest.java
- openapi-generator/src/test/resources/3_0/discriminatorconstructorbug.yml
- openapi-generator/src/test/resources/3_0/readonlyconstructorbug.yml
> Fixed incorrect contructors with discriminator and readonly in generator.

- openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientCodegen.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/MicronautClientCodegenTest.java
- openapi-generator/src/test/resources/3_0/inputStream.yml
> Add import java.io.InputStream to generated api client class

- openapi/src/main/java/io/micronaut/openapi/view/AbstractViewConfig.java
- openapi/src/main/java/io/micronaut/openapi/view/SwaggerUIConfig.java
- openapi/src/main/java/io/micronaut/openapi/visitor/ConfigUtils.java
- openapi/src/test/groovy/io/micronaut/openapi/view/OpenApiOperationViewRenderSpec.groovy
> Added lost contextPath to swaggerUi with groups

- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/ElementUtils.java
- openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
> Fixed process extra body parameters.

- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerCodegen.java
- openapi-generator/src/main/resources/templates/java-micronaut/client/api.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/client/auth/Authorization.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/client/auth/AuthorizationBinder.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/client/auth/AuthorizationFilter.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/client/auth/Authorizations.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/client/auth/configuration/ApiKeyAuthConfiguration.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/client/auth/configuration/ConfigurableAuthorization.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/client/auth/configuration/HttpBasicAuthConfiguration.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/client/params/type.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/model.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/oneof_interface.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/pojo.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/server/controller-implementation.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/server/controller-interface.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/server/params/type.mustache
- openapi-generator/src/test/java/io/micronaut/openapi/generator/AbstractMicronautCodegenTest.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/MicronautClientCodegenTest.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/MicronautServerCodegenTest.java
- openapi-generator/src/test/resources/3_0/modelwithprimitivelist.yml
- test-suite-server-generator/build.gradle
- test-suite-server-generator/spec.yaml
- test-suite-server-generator/src/main/java/io/micronaut/openapi/test/api/RequestBodyController.java
- test-suite-server-generator/src/main/java/io/micronaut/openapi/test/api/ResponseBodyController.java
- test-suite-server-generator/src/test/groovy/io/micronaut/openapi/test/api/RequestBodyControllerSpec.groovy
- test-suite-server-generator/src/test/groovy/io/micronaut/openapi/test/api/ResponseBodyControllerSpec.groovy
> Added generating generic annotations to generator.

- gradle/libs.versions.toml
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiSchemaGenericsSpec.groovy
> Fix process arrays and iterables with generic placeholders

- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
- openapi-generator/src/test/resources/3_0/propWithSecondUpperCaseChar.yml
> Fix generator for properties with second upper case char

- openapi-generator/src/main/resources/templates/java-micronaut/common/model/pojo.mustache
- openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautServerCodegenTest.java
> Add default private constructor only when we have required args constructor

- openapi-generator/build.gradle
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiEndpointVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/ContextUtils.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiIncludeVisitor.java
- openapi/src/main/java/io/micronaut/openapi/visitor/SchemaUtils.java
- openapi/src/main/java/io/micronaut/openapi/visitor/security/InterceptUrlMapConverter.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiBasicSchemaSpec.groovy
- test-suite-java-server-generator/build.gradle
Fixed #1346
See discussion here: https://github.com/micronaut-projects/micronaut-core/issues/10242
> Fix empty oneOf, anyOf lists

- gradle/libs.versions.toml
- openapi-generator/build.gradle
- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientOptionsBuilder.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerOptionsBuilder.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautClientOptionsBuilder.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/KotlinMicronautServerOptionsBuilder.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/MicronautCodeGeneratorEntryPoint.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
- openapi-generator/src/main/resources/templates/java-micronaut/common/operationAnnotations.mustache
- openapi-generator/src/main/resources/templates/kotlin-micronaut/common/operationAnnotations.mustache
- openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautServerCodegenTest.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautServerCodegenTest.java
- openapi-generator/src/test/resources/3_0/plural.yml
- test-suite-kotlin-ksp-server-generator/src/main/kotlin/io/micronaut/openapi/test/api/RequestBodyController.kt
Remove `@Parameter` annotation for body parameter
> Add auto plural to generate request body parameter name, when it unnamed collection.

- .github/workflows/gradle.yml
- .github/workflows/release.yml
Close: https://github.com/micronaut-projects/micronaut-openapi/pull/1356
see: https://github.com/actions/upload-artifact/releases/tag/v4.0.0 and https://github.com/micronaut-projects/micronaut-project-template/pull/430
> ci: GitHub Actions upload-artifacts @v4

- openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautServerCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/model.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/common/params/validation.mustache
- openapi-generator/src/main/resources/templates/java-micronaut/server/controller-interface.mustache
- openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautServerCodegenTest.java
> deprecate @HardNullable

- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/Utils.java
- openapi-generator/src/main/resources/templates/java-micronaut/common/model/enum.mustache
- openapi-generator/src/main/resources/templates/kotlin-micronaut/common/model/enum.mustache
- openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
- openapi-generator/src/test/resources/3_0/enum.yml
> Fix generating non string enums

- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
- openapi-generator/src/test/resources/3_0/underscore.yml
> Fix generating property names from reserved name list and started by underscore. Example: '_default'

- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
- openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautKotlinCodegen.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/JavaMicronautClientCodegenTest.java
- openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java
- openapi-generator/src/test/resources/3_0/propWithSecondUpperCaseChar.yml
Restores allcaps behavior that changed in https://github.com/micronaut-projects/micronaut-openapi/issues/1226
> Restore all-caps property generation

- openapi/src/main/java/io/micronaut/openapi/visitor/ConvertUtils.java
- openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiEnumSpec.groovy
See: https://github.com/swagger-api/swagger-core/issues/4466
> Fix enum process, when @JsonValue is on an interface method
